### ISSUE TITLE
[diamonds-project] Javier Pérez

### ISSUE THREAD

**Issue by BlueJotas** [ironhack-datalabs/datamad1020-rev#557]
https://github.com/BlueJotas/Kaggle-competition

**Comment by olmocorell** [comment]
¡Javiiiiiiiiii! 💪🏻 🚀 

Enhorabuena, has hecho muy buen trabajo y el readme está súper. Has entrenado unos cuantos algoritmos y está genial.
Tus jupyters están muy bien organizados así que tu proyecto está perfect.
Podrías haber hecho un pipeline para entrenar varios modelos del tirón y de ahí elegir el mejor y tunear sus hiperparámetros, pero está muy muy bien que hayas hecho el gridsearch para buscar los mejores parámetros en varios modelos.
Muy buen trabajo ¡¡enhorabuena!!


![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102013343-c3b40e00-3d4f-11eb-9e41-4921633ae626.jpg)
