### ISSUE TITLE
[diamonds-project] Jose Manuel

### ISSUE THREAD

**Issue by JoseManuel-G** [ironhack-datalabs/datamad1020-rev#558]
https://github.com/JoseManuel-G/diamonds-project.git

**Comment by breogann** [comment]
José! 🙋🏻‍♂️

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: se te ha quedado un archivo temporal/oculto:

        Para borrar:

        ```python
         git rm --cached .ipynb_checkpoints
        ```

        para ignorar de forma recursiva: 

        ```python
        */**.ipynb_checkpoints
        ```

    - El jupyter: no tiene nombre y está un poco desordenado. Aprovecha los títulos de markdown para darle (más) forma y que de un vistazo se vea el proceso que has seguido.   Quizá un jupyter por cada modelo que entrenas.
- El **[README.md](http://readme.md) ✍🏻**:
    - Al README le puedes añadir muchas más cosas. No has añadido enlace a los datos y es una explicación justa para lo que has estado haciendo.
- El **código 👩‍💻:**
    - Joséeeeee, todos los import arriba 🔪

En resumen, para esto proyecto hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar con unos determinados datos:

- Limpieza de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

- **Encoders**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179)
- **Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
- Modelo de regresión/categorización: probar varios 🤷🏻‍♂️, [aquí](https://mahiprashanth866.medium.com/top-10-best-machine-learning-algorithms-acd9fd2c0471) y [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
- **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

Además de las clases de Ignacio y Sheriff, te dejo unos artículos que resumen muy bien cada punto para referencia futura. Como has visto, Machine learning no es más que estadística.

Es cierto que este proyecto era diferente al resto en cuanto a la organización y el la estructura que tenía que tener, pero si quieres dejar el repositorio mejor, puedes hacer los cambios que te comento. 

En cualquier caso, aunque el repo esté hecho un poco manga por hombro, has procesado datos y has entrenado varios modelos de machine learning para hacer la submission en Kaggle, que era el objetivo 🎉

Sigue así José!! A darle duro al proyecto final!  🚀

![image](https://user-images.githubusercontent.com/54676992/102360860-d7ab7a00-3fb2-11eb-84a4-098089648963.png)
