### ISSUE TITLE
[diamonds-project] Mario Sainz

### ISSUE THREAD

**Issue by Mario-Sainz** [ironhack-datalabs/datamad1020-rev#559]
https://github.com/Mario-Sainz/diamonds-project.git

**Comment by olmocorell** [comment]
¡Hola MariooooooooooooO! 💪🏻 🚀 🔥 
En primer lugar.... si tienes una carpeta data, ¿por qué están fuera los datos de train y test?

<img width="932" alt="Captura de pantalla 2020-12-13 a las 22 33 21" src="https://user-images.githubusercontent.com/57899051/102024583-35fa1200-3d93-11eb-8d40-a09d0932a9e5.png">

Por otra parte ¿dónde haces análisis y limpieza de los datos? deberías tener un jupyter dedicado a esa misión. Si te dejas eso hecho y exportas los datos no tienes que hacerlo una y otra vez cuando entrenas los modelos.

Por otra parte está genial que hayas entrenado varios modelos, podías haber buscado alguno más que 4 era el mínimo....pero bueno, está muy bien que hayas hecho grid search para tunear hiperparámetros y que hayas revisado algunas métricas.

Así que, en general, buen trabajo Mario. Espero que estés a tope con tu proyecto final y que todo vaya sobre ruedas.
¡¡¡Seguimooooooooooooos!!!!


![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102025574-2da4d580-3d99-11eb-9abb-2f54060a94e7.jpg)
