### ISSUE TITLE
[diamonds-project] Sonia Quintanar

### ISSUE THREAD

**Issue by sonia-quintanar** [ironhack-datalabs/datamad1020-rev#560]
Enlace al proyecto:

https://github.com/sonia-quintanar/diamonds-project.git

**Comment by olmocorell** [comment]
¡Hola Sonia! 🚀 💪🏻 
No me entretengo mucho en este proyecto, porque ya se ven los resultados del trabajo en la competición de kaggle y me refiero no a la posición en la tabla si no a la cantidad de submissions...
Espero que te hayan quedado claros algunos conceptos del ML.
Por mi parte, decirte que si tienes alguna duda cuentes conmigo.
En este repo me faltan jupyter donde yo pueda ver la limpieza y exploración de los datos, los diferentes modelos, el grid search que podrías haberle hecho a cada uno para elegir los hiperparámetros más adecuados.... todo eso.

Te lo digo para que lo tengas en cuenta por si lo tienes por ahí, que lo subas a github.

Entiendo que son conceptos complicados y avanzados y que estás trabajando en ello y ahora estamos con el proyecto final, pero estaré encantada de echarte un cable en cualquier cosa que necesites.


¡¡Mucho ánimo!!


![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102023040-119a3780-3d8b-11eb-9848-cb4d22cbed28.jpg)
