### ISSUE TITLE
[diamonds-project] Luciana Lescano

### ISSUE THREAD

**Issue by LucianaLescano** [ironhack-datalabs/datamad1020-rev#561]
My link: https://github.com/LucianaLescano/project6-diamonds_project

**Comment by breogann** [comment]
Lucianaaaaa! 🙋🏻‍♂️

- Respecto a la **organización del repositorio 📚**
    - Pues mira, la verdad que todobien. Quizá puedes separar data en input y output, pero no es necesario.
    - Gracias por haber separado los jupyters.
- El **[README.md](http://readme.md) ✍🏻**:
    - Está bien! (siempre se le puede añadir más; por ejemplo los modelos que has utilizado)
- El **código 👩‍💻:**
    - Veo que has ido importando las funciones según te han ido haciendo falta. Te diría que mejor las importes todas arriba.
    - Para este proyecto no era necesario modularizar las funciones, pero es súper buena práctica.
    - Uf, ¿has hecho los docstrings diciendo qué hay de input y qué de output? GENIAL.

En resumen, para esto proyecto hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar con unos determinados datos:

- Limpieza de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como é[sta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos. Existiendo encoder, mejor encoder 🙂).
2. **Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. Modelo de regresión/categorización: probar varios 🤷🏻‍♂️, [aquí](https://mahiprashanth866.medium.com/top-10-best-machine-learning-algorithms-acd9fd2c0471) y [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

Además de las clases de Ignacio y Sheriff, te dejo unos artículos que resumen muy bien cada punto para referencia futura. Como has visto, Machine learning no es más que estadística.

En cualquier caso, el proyecto está genial. Aunque no consiguieras las mejores métricas, has procesado datos y has entrenado varios modelos de machine learning para hacer la submission en Kaggle, que era el objetivo 🎉

Sigue así Luciana!! A darle duro al proyecto final!  🚀

![image](https://user-images.githubusercontent.com/54676992/102362797-14787080-3fb5-11eb-943d-f86a8dd7fb83.png)
