### ISSUE TITLE
[diamonds-project] Patricia Carrasco

### ISSUE THREAD

**Issue by patri-carrasco** [ironhack-datalabs/datamad1020-rev#563]
https://github.com/patri-carrasco/diamonds-project

**Comment by olmocorell** [comment]
¡Patriiiiiiiiii! 🚀 💪🏻 
No me voy a entretener mucho en este proyecto porque básicamente era un entrenamiento para hacer ML
Pero sí que me gustaría un par de cosas.
En primer lugar, enhorabuena porque has probado un montón de algoritmos y eso era justo lo que había que hacer, no solo eso sino que además has hecho grid search con cv y eso está genial, así es como hay que hacerlo, para tunear de forma apropiada los hiper parámetros en función de los datos. 
Lo único es que tus jupyter están un poco desordenados, entrenas en unos lugares y en otros.... lo ideal sería que tuvieras la limpieza centralizada en un jupyter. 
Luego, si quieres probar a editar los datos en función de cada algoritmo, que puede ser, lo ideal sería ir comentando por qué haces una cosa u otra ... y bueno, en el jupyter de cada algoritmo pues simplemente hacer el grid search con los hiper parámetros de cada algoritmo, sacar los mejores parámetros, entrenar con todos los datos y hacer la submission.

Pero bueno, que has hecho muy buen trabajo y que está súper.
Al final es todo cuestión de organización para que se vea limpio el repo y para que te sirva a ti para entender de cara al futuro cuando eches mano de ellos.

¡¡SEGUIMOS A TOPEEEEEEEEEEEEEEEEEEEEE!!


![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102023450-b5d0ae00-3d8c-11eb-81cf-dae9f5104d45.jpg)
