### ISSUE TITLE
[diamonds-project] Jaime Calcedo

### ISSUE THREAD

**Issue by JaimeCalcedo** [ironhack-datalabs/datamad1020-rev#566]

**Comment by breogann** [comment]
Jaimeee! 🙋🏻‍♂️

Abriste el issue pero no pusiste el enlace 👀

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: se te ha quedado un archivo temporal/oculto. He visto que tu último commit era para borrarlo, pero para eso tienes que decirle a git que lo borre de su caché.

        Para borrar:

        ```python
         git rm --cached .DS_Store
        ```

        para ignorar de forma recursiva: 

        ```python
        */**.DS_Store
        ```

    - Pues mira, la verdad que todobien.
- El **[README.md](http://readme.md) ✍🏻**:
    - Pues como te decía, *todobien*. Si quieres, le puedes añadir el tipo de datos que tiene el dataset y/o alguna captura de los datos.
- El **código 👩‍💻:**
    - Súper bien haber puesto la limpieza en funciones para importarlas luego 👏🔝
    - Genial también por ir guiando los jupyters
    - Poco más que decirte, está todo genial Jaime!

En resumen (y esto lo pongo a modo de resumen literal, pero vamos, que sacaste pedazo de puntuación así que qué te voy a decir), para esto proyecto hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar con unos determinados datos:

- Limpieza de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders & Standarization**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como é[sta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos. Existiendo encoder, mejor encoder 🙂).
2. **Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. Modelo de regresión/categorización: probar varios 🤷🏻‍♂️, [aquí](https://mahiprashanth866.medium.com/top-10-best-machine-learning-algorithms-acd9fd2c0471) y [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

Además de las clases de Ignacio y Sheriff, te dejo unos artículos que resumen muy bien cada punto para referencia futura. Como has visto, Machine learning no es más que estadística.

En cualquier caso, el proyecto está genial. Has procesado datos y has entrenado varios modelos de machine learning para hacer la submission en Kaggle, que era el objetivo 🎉

Sigue así Jaime!! A darle duro al proyecto final!  🚀

![image](https://user-images.githubusercontent.com/54676992/102391642-46e69580-3fd6-11eb-80cd-5d501ad6e370.png)
