### ISSUE TITLE
[diamonds-project] Juan Marin

### ISSUE THREAD

**Issue by juanmarin00** [ironhack-datalabs/datamad1020-rev#568]
https://github.com/juanmarin00/diamond-price-prediction

**Comment by breogann** [comment]
Hola Juan,

Aunque el proyecto consistiera en hacer submissions a Kaggle con el modelo entregado, también tenéis que tener un repositorio con los datos, el procesamiento y el readme. No nos interesa sólo la métrica, sino el proceso y las técnicas que habéis utilizado para llegar a ese valor.
