### ISSUE TITLE
[diamonds-project] Rafael Rodríguez Cancela

### ISSUE THREAD

**Issue by rafadedubra** [ironhack-datalabs/datamad1020-rev#569]
[https://github.com/rafadedubra/diamonds]

**Comment by rafadedubra** [comment]
Estoy trabajando para poner el readme bonito y subir una presentación ;)

**Comment by olmocorell** [comment]
Rafaaaaaaaaaaaaaa!! 🚀 💪🏻 

El proyecto sin readme está invalid y eso es == no entregado.
Te lo voy a corregir pero, por favor, haz un readme cuando puedas ¿vale?

El jupyter de exploración y limpieza está guay. 

Está genial que hayas hecho el pipeline para ver todas las métricas de los modelos. Luego, una vez has elegido el que mejor RMSE tenía te podías haber hecho un grid search para tunear los hiperparámetros y ver cómo ajustarlo mejor.
Por otra parte, la métrica más adecuada era el MSE, lo ponía en la competición ya que hicimos un ajuste de los datos...

Pero bueno ¡¡buen trabajo!!

![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102013126-6a97aa80-3d4e-11eb-836b-699d9af5558a.jpg)
