### ISSUE TITLE
[diamonds-project] Sergio Gonzalez 

### ISSUE THREAD

**Issue by sgonzalainen** [ironhack-datalabs/datamad1020-rev#570]
https://github.com/sgonzalainen/IronHack-Project6-Inclass_ML_Competition

![image](https://user-images.githubusercontent.com/68953494/101290954-91615880-3805-11eb-975e-755ee40b5848.png)

**Comment by olmocorell** [comment]
¡¡Sergiooooooooo!! 💪🏻 🚀 

Como vimos esto en clase estoy pasando rápido por aquí.
Tu readme está impecable.
Todo está bien, ganaste la competición y has demostrado que sabes jugar a esto del ML así que enhorabuena.
El .py genial.
Podías haber separado los jupyters en limpieza, exportarte los datos y luego... pues no sé, un pipeline en un jupyter para ver el modelo que de primeras se ajustaba más y luego cada modelo con su grid search en otros jupyter, pero bueno, por ponerme finolis. 
Que está perfecto.

¡Dale duro a ese proyectazo final! ¡¡Enhorabuenaaaaaaaaaa!!


![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102013394-2c9b8600-3d50-11eb-84bb-0675c1d3b0a0.jpg)
