### ISSUE TITLE
[diamonds-project] Juan Pérez Llorente 

### ISSUE THREAD

**Issue by jperezllorente** [ironhack-datalabs/datamad1020-rev#573]
https://github.com/jperezllorente/diamond-project.git

**Comment by breogann** [comment]
Juanpee! 🙋🏻‍♂️

- Respecto a la **organización del repositorio 📚**
    - Pues mira, la verdad que todobien.
- El **[README.md](http://readme.md) ✍🏻**:
    - Pues como te decía, *todobien*. Si quieres, le puedes añadir el tipo de datos que tiene el dataset y/o alguna captura de los datos.
- El **código 👩‍💻:**
    - Genial también por ir guiando los jupyters
    - Súper limpios los jupyters. Sólo con lo justo 👏
    - Poco más que decirte, está todo genial Juanpe!

En resumen (y esto lo pongo a modo de resumen literal, pero vamos, que sacaste pedazo de puntuación así que qué te voy a decir), para esto proyecto hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar con unos determinados datos:

- Limpieza de los datos
- Cómo separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.

Para cada uno de ellos hay una estrategia:

1. **Encoders & Standarization**: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como é[sta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos. Existiendo encoder, mejor encoder 🙂).
2. **Cross-validation:** para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/introduction-to-cross-validation-k-fold-7ed9cbd0ed7b)
3. Modelo de regresión/categorización: probar varios 🤷🏻‍♂️, [aquí](https://mahiprashanth866.medium.com/top-10-best-machine-learning-algorithms-acd9fd2c0471) y [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
4. **Grid search**: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)

Además de las clases de Ignacio y Sheriff, te dejo unos artículos que resumen muy bien cada punto para referencia futura. Como has visto, Machine learning no es más que estadística.

En cualquier caso, el proyecto está genial. Has procesado datos y has entrenado varios modelos de machine learning para hacer la submission en Kaggle, que era el objetivo 🎉

Sigue así Juanpe!! A darle duro al proyecto final!  🚀

![image](https://user-images.githubusercontent.com/54676992/102393098-3800e280-3fd8-11eb-8bbf-43b7c66e0d5b.png)
