### ISSUE TITLE
[diamons-project] Nuria Peñas

### ISSUE THREAD

**Issue by Nuria-Pe** [ironhack-datalabs/datamad1020-rev#576]
https://github.com/Nuria-Pe/Diamons-Project.git

**Comment by olmocorell** [comment]
¡¡Hola Nuriaaaaaa!! 🚀 💪🏻 🔥 

No me voy a enredar mucho por aquí porque estuvimos viendo estos proyectos en clase el otro día. Y este proyecto era básicamente probar algoritmos de ML.
Te cuento solo que puedes darle un poco de caña al readme.
Por otra parte, con respecto a los jupyter notebooks.
El de limpieza está guay, podías haber hecho una exploración un poco más exhaustiva de los datos para ver si había columnas colineales o algunas columnas que dieran información que ya había en otras columnas para quedarnos con algunas o incluso ponderar otras en función de su importancia...

Por otra parte, está súper que hayas hecho grid search en cada modelo para ver cuáles eran los parámetros más adecuados. Enhorabuena por eso!!
Espero que con este proyecto hayas aclarado conceptos de machine learning.

¡¡Buen trabajo!!

![its-easy-just-5bd65c](https://user-images.githubusercontent.com/57899051/102022977-ae100a00-3d8a-11eb-8145-316563ba37fc.jpg)
